apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 9092
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "NodePort" }}
  nodePort: {{ .Values.service.nodePort }}
  {{- end }}
